DRAFT: Test ruff's monorepo processing

diff --git a/.github/workflows/test_and_deploy.yml b/.github/workflows/test_and_deploy.yml
--- a/.github/workflows/test_and_deploy.yml
+++ b/.github/workflows/test_and_deploy.yml
@@ -30,6 +30,30 @@ jobs:
         run: |
           ./scripts/test.sh format
 
+  python-lint:
+    name: Lint Python code with ruff
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: astral-sh/ruff-action@v3
+      # Ruff monorepo processing experiment begins here...
+      - uses: actions/checkout@v4
+        with:
+          submodules: 'recursive'  # Add the pymavlink submodule which has ruff errors.
+      - run: ruff check --exit-zero  # Show pymavlink's errors but don't fail the job.
+      - name: "Apply ArduPilot/pymavlink#1080"
+        run: |
+          pushd pymavlink
+          echo -e '\n[tool.ruff]\nlint.extend-ignore=["E4","E7","F40","F523","F601","F811","F841"]' >> pyproject.toml
+          pipx run pyproject-fmt pyproject.toml || true
+          pipx run --spec="validate-pyproject[all]" validate-pyproject pyproject.toml
+          popd
+      # Okay, so this is the cool part: We run ruff on the whold (mono)repo.
+      # When ruff is testing inside the pymavlink submodule, it will apply rules
+      # based on pymavlink/pyproject.toml but when testing the rest of the repo,
+      # it will apply rules based on the root ruff.toml file.
+      - name: "Single ruff check with multiple rule sets"
+        run: ruff check  # All checks passed!
   python-tests:
     name: Python ${{ matrix.python-version }} tests
     runs-on: ubuntu-22.04
@@ -100,7 +124,7 @@ jobs:
 
   deploy:
     name: Generate and push C headers
-    needs: [format, python-tests, node-tests]
+    needs: [format, python-lint, python-tests, node-tests]
     runs-on: ubuntu-22.04
     if: github.ref == 'refs/heads/master'
     env:
